version: "3.9"

services:
  squid1:
    image: sameersbn/squid:4.13-2
    container_name: squid1
    ports:
      - "15001:3128"
      - "15002:3129"
      - "15003:3130"
    env_file:
      - .env
    volumes:
      - ./instance1/conf/squid.conf:/etc/squid/squid.conf:ro
      - ./instance1/cache:/var/spool/squid

  squid2:
    image: sameersbn/squid:4.13-2
    container_name: squid2
    ports:
      - "15004:3128"
      - "15005:3129"
      - "15006:3130"
    env_file:
      - .env
    volumes:
      - ./instance2/conf/squid.conf:/etc/squid/squid.conf:ro
      - ./instance2/cache:/var/spool/squid
